# Scout de finalizações

## Pergunta

Quais jogadores da amostra produziram mais perigo com suas finalizações?

## Fonte dos dados

StatsBomb Open Data.

## Métricas

- Finalizações
- Gols
- xG acumulado
- xG por finalização
- Gols menos xG

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

from statsbombpy import sb

Matplotlib is building the font cache; this may take a moment.

In [3]:
competitions = sb.competitions()

competitions.head()

/Users/th3g3ntl3man/Documents/github/european-player-scout/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093,2025-11-15T23:17:41.827093,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,NaN,NaN,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694,NaN,2026-05-15T15:54:04.598614
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,NaN,2024-02-13T02:35:28.134882

In [5]:
competitions[
    [
        "competition_id",
        "season_id",
        "country_name",
        "competition_name",
        "season_name",
        "competition_gender",
    ]
].drop_duplicates()

,competition_id,season_id,country_name,competition_name,season_name,competition_gender
0,9,281,Germany,1. Bundesliga,2023/2024,male
1,9,27,Germany,1. Bundesliga,2015/2016,male
2,1267,107,Africa,African Cup of Nations,2023,male
3,16,4,Europe,Champions League,2018/2019,male
4,16,1,Europe,Champions League,2017/2018,male
...,...,...,...,...,...,...
75,35,75,Europe,UEFA Europa League,1988/1989,male
76,53,315,Europe,UEFA Women's Euro,2025,female
77,53,106,Europe,UEFA Women's Euro,2022,female
78,72,107,International,Women's World Cup,2023,female
79,72,30,International,Women's World Cup,2019,female

In [7]:
COMPETITION_ID = 9
SEASON_ID = 281

In [10]:
matches = sb.matches(
    competition_id = COMPETITION_ID,
    season_id = SEASON_ID,
)

matches[
    [
        "match_id",
        "match_date",
        "home_team",
        "away_team",
        "home_score",
        "away_score",
    ]
].head()

/Users/th3g3ntl3man/Documents/github/european-player-scout/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,match_id,match_date,home_team,away_team,home_score,away_score
0,3895292,2024-04-06,Union Berlin,Bayer Leverkusen,0,1
1,3895320,2024-04-27,Bayer Leverkusen,VfB Stuttgart,2,2
2,3895158,2023-12-03,Bayer Leverkusen,Borussia Dortmund,1,1
3,3895107,2023-10-08,Bayer Leverkusen,FC Köln,3,0
4,3895340,2024-05-12,Bochum,Bayer Leverkusen,0,5

In [11]:
sample_matches = matches.head(5)

sample_matches[
    ["match_id", "home_team", "away_team"]
]

   match_id         home_team          away_team
0   3895292      Union Berlin   Bayer Leverkusen
1   3895320  Bayer Leverkusen      VfB Stuttgart
2   3895158  Bayer Leverkusen  Borussia Dortmund
3   3895107  Bayer Leverkusen            FC Köln
4   3895340            Bochum   Bayer Leverkusen

In [12]:
events = pd.concat(
    [
        sb.events(match_id=match_id)
        for match_id in sample_matches["match_id"]
    ],
    ignore_index=True
)

events.shape

/Users/th3g3ntl3man/Documents/github/european-player-scout/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:23: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

(19044, 105)

In [13]:
events.columns.tolist()

['50_50',
 'ball_receipt_outcome',
 'ball_recovery_offensive',
 'ball_recovery_recovery_failure',
 'block_deflection',
 'block_offensive',
 'carry_end_location',
 'clearance_aerial_won',
 'clearance_body_part',
 'clearance_head',
 'clearance_left_foot',
 'clearance_right_foot',
 'counterpress',
 'dribble_nutmeg',
 'dribble_outcome',
 'dribble_overrun',
 'duel_outcome',
 'duel_type',
 'duration',
 'foul_committed_advantage',
 'foul_committed_card',
 'foul_committed_penalty',
 'foul_committed_type',
 'foul_won_advantage',
 'foul_won_defensive',
 'goalkeeper_body_part',
 'goalkeeper_end_location',
 'goalkeeper_outcome',
 'goalkeeper_position',
 'goalkeeper_technique',
 'goalkeeper_type',
 'id',
 'index',
 'injury_stoppage_in_chain',
 'interception_outcome',
 'location',
 'match_id',
 'minute',
 'miscontrol_aerial_won',
 'off_camera',
 'out',
 'pass_aerial_won',
 'pass_angle',
 'pass_assisted_shot_id',
 'pass_body_part',
 'pass_cross',
 'pass_cut_back',
 'pass_deflected',
 'pass_end_location',
 'pass_height',
 'pass_inswinging',
 'pass_length',
 'pass_outcome',
 'pass_outswinging',
 'pass_recipient',
 'pass_recipient_id',
 'pass_shot_assist',
 'pass_switch',
 'pass_technique',
 'pass_through_ball',
 'pass_type',
 'period',
 'play_pattern',
 'player',
 'player_id',
 'position',
 'possession',
 'possession_team',
 'possession_team_id',
 'related_events',
 'second',
 'shot_aerial_won',
 'shot_body_part',
 'shot_end_location',
 'shot_first_time',
 'shot_freeze_frame',
 'shot_key_pass_id',
 'shot_outcome',
 'shot_statsbomb_xg',
 'shot_technique',
 'shot_type',
 'substitution_outcome',
 'substitution_outcome_id',
 'substitution_replacement',
 'substitution_replacement_id',
 'tactics',
 'team',
 'team_id',
 'timestamp',
 'type',
 'under_pressure',
 'bad_behaviour_card',
 'goalkeeper_shot_saved_to_post',
 'pass_goal_assist',
 'pass_no_touch',
 'shot_deflected',
 'shot_one_on_one',
 'shot_saved_to_post',
 'dribble_no_touch',
 'shot_open_goal',
 'clearance_other',
 'foul_committed_offensive',
 'pass_straight',
 'foul_won_penalty',
 'pass_miscommunication']

In [14]:
events["type"].value_counts().head(15)

type
Pass              5389
Ball Receipt*     5221
Carry             4454
Pressure          1491
Ball Recovery      480
Duel               306
Block              232
Clearance          185
Goal Keeper        177
Shot               146
Miscontrol         133
Dribble            130
Foul Committed     116
Foul Won           114
Dispossessed       111
Name: count, dtype: int64

In [23]:
shots = events.loc[
    events["type"].eq("Shot"),
    [
        "match_id",
        "player",
        "team",
        "minute",
        "shot_outcome",
        "shot_statsbomb_xg",
        "shot_type",
    ]
].copy()

In [24]:
shots["is_goal"] = (
    shots["shot_outcome"]
    .eq("Goal")
    .astype(int)
)

In [25]:
ranking = (
    shots
    .dropna(subset=["player"])
    .groupby(["player", "team"], as_index=False)
    .agg(
        shots=("player", "size"),
        goals=("is_goal", "sum"),
        total_xg=("shot_statsbomb_xg", "sum"),
        xg_per_shot=("shot_statsbomb_xg", "mean"),
    )
)

In [27]:
ranking["goals_minus_xg"] = (
    ranking["goals"] - ranking["total_xg"]
)

In [29]:
ranking = ranking.sort_values(
    "total_xg",
    ascending=False,
)

ranking.head(10)

,player,team,shots,goals,total_xg,xg_per_shot,goals_minus_xg
42,Victor Okoh Boniface,Bayer Leverkusen,13,3,3.513382,0.270260,-0.513382
1,Alejandro Grimaldo García,Bayer Leverkusen,12,1,1.681677,0.140140,-0.681677
3,Amine Adli,Bayer Leverkusen,10,2,1.450749,0.145075,0.549251
41,Serhou Guirassy,VfB Stuttgart,6,0,1.434243,0.239041,-1.434243
21,Jeremie Frimpong,Bayer Leverkusen,8,1,1.280093,0.160012,-0.280093
22,Jonas Hofmann,Bayer Leverkusen,8,1,1.169579,0.146197,-0.169579
15,Florian Wirtz,Bayer Leverkusen,9,1,1.117599,0.124178,-0.117599
35,Patrik Schick,Bayer Leverkusen,9,1,0.858553,0.095395,0.141447
13,Eric Martel,FC Köln,2,0,0.735629,0.367815,-0.735629
39,Robert Andrich,Bayer Leverkusen,8,1,0.509345,0.063668,0.490655

In [32]:
ranking_display = ranking.copy()

columns_to_round = [
    "total_xg",
    "xg_per_shot",
    "goals_minus_xg",
]

ranking_display[columns_to_round] = (
    ranking_display[columns_to_round].round(2)
)

ranking_display.head(10)

,player,team,shots,goals,total_xg,xg_per_shot,goals_minus_xg
42,Victor Okoh Boniface,Bayer Leverkusen,13,3,3.51,0.27,-0.51
1,Alejandro Grimaldo García,Bayer Leverkusen,12,1,1.68,0.14,-0.68
3,Amine Adli,Bayer Leverkusen,10,2,1.45,0.15,0.55
41,Serhou Guirassy,VfB Stuttgart,6,0,1.43,0.24,-1.43
21,Jeremie Frimpong,Bayer Leverkusen,8,1,1.28,0.16,-0.28
22,Jonas Hofmann,Bayer Leverkusen,8,1,1.17,0.15,-0.17
15,Florian Wirtz,Bayer Leverkusen,9,1,1.12,0.12,-0.12
35,Patrik Schick,Bayer Leverkusen,9,1,0.86,0.10,0.14
13,Eric Martel,FC Köln,2,0,0.74,0.37,-0.74
39,Robert Andrich,Bayer Leverkusen,8,1,0.51,0.06,0.49